version: '3.8'

services:
  pheromind:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py", "agent_inputs/goal.md"]
